window.LANG_EN = {
    "page_title": "Refrin — Home",
    "nav_productos": "PRODUCTS",
    "nav_nosotros": "OUR COMPANY",
    "nav_contacto": "CONTACT",

    "hero_title": "SANITARY PANELS FOR WALLS AND CEILINGS",
    "hero_sub": "FRP PANELS (FIBERGLASS REINFORCED PLASTIC)",

    "empresa_title": "OUR COMPANY",
    "empresa_p1": "Founded in 1943 as an engineering consultancy firm for complete industrial projects (civil, electromechanical, and industrial refrigeration works).",
    "empresa_p2": "In 1959, Refrin expanded its operations to include the manufacture and installation of industrial refrigeration equipment (evaporators, condensers, plate freezers, pressure vessels, etc.), offering a wide range of solutions for the cooling, freezing, and storage of food products.",
    "empresa_p3": "Since 1993, we have been the exclusive representatives for Mercosur of the English firm Storax Racking System, which was acquired by the Belgian Stow Group, a world leader in the provision of high-density mobile racks for cold storage and distribution centers.",
    "empresa_p4": "We also represent the German firm Lamilux, a world leader in the manufacture of FRP (Fiberglass Reinforced Plastic) sanitary panels. We were pioneers in Argentina importing and installing FRP material, a business that we began in 1980.",
    "empresa_p5": "With a history over 80 years, Refrin offers the best solutions for the food industry.",
    "empresa_image_alt": "History of Refrin",

    "productos_title": "OUR PRODUCTS",

    "product_heading_1": "1 - SANDWICH INSULATED PANELS WITH FRP SHEETS",
    "p1_li1": "SELF-SUPPORTING PANEL",
    "p1_li2": "EXPANDED POLYSTYRENE (EPS) CORE",
    "p1_li3": "INJECTED POLYURETHANE (PUR AND PIR) CORE",
    "p1_li4": "ROCK WOOL (LDR) CORE",
    "p1_li5": "VARIABLE THICKNESSES BETWEEN 40 AND 200 mm",
    "p1_li6": "FRP THICKNESS BETWEEN 1.2 AND 2.0 mm",
    "p1_li7": "USABLE WIDTH 1.00 / 1.22 m",
    "p1_li8": "VERY EASY TO INSTALL",
    "p1_li9": "DRY-CLEAN CONSTRUCTION",

    "product_heading_2": "2 - FRP WALL PANELS",

    "slide_2_1": "EMBOSSED FRP",
    "slide_2_2": "SMOOTH FRP",
    "slide_2_3": "HIGH IMPACT FRP",
    "slide_2_4": "ANTIBACTERIAL FRP",

    "product_heading_3": "2 - FRP WALL PANELS",
    "p2_li1": "HIGH RESISTANCE TO MOISTURE AND MOLD",
    "p2_li2": "HIGH RESISTANCE TO CHEMICAL AGENTS",
    "p2_li3": "EASY TO CLEAN",
    "p2_li4": "GELCOAT FINISH, UV PROTECTIVE LAYER",
    "p2_li5": "PANEL THICKNESSES BETWEEN 1.00 AND 2.2 mm",
    "p2_li6": "VERY EASY INSTALLATION",
    "p2_li7": "COMPLIES WITH HYGIENE AND FOOD SAFETY STANDARDS",
    "p2_li8": "HIGH BRIGHTNESS AND COLOR PERMANENCE",
    "p2_li9": "VERY LOW MAINTENANCE COST",

    "product_heading_4": "3 - FRP PANELS FOR KITCHEN CEILINGS",
    "p3_li1": "COMPLETELY SANITARY",
    "p3_li2": "MAINTENANCE-FREE",
    "p3_li3": "QUICK AND EASY INSTALLATION",
    "p3_li4": "EASY TO CLEAN",
    "p3_li5": "DIMENSIONS: 61 x 61 cm",
    "p3_li6": "DRY CONSTRUCTION",
    "p3_li7": "METAL OR PLASTIC GRILL",
    "p3_li8": "IDEAL FOR INDUSTRIAL KITCHENS",
    "p3_li9": "IDEAL FOR RESTAURANT AND FAST FOOD KITCHENS",

    "product_heading_5": "4 - SANITARY ACCESSORIES",

    "product_heading_6": "5 - FRP DECORATION PANELS",
    "p4_li1": "FOR ARCHITECTURAL AND INTERIOR DESIGNS",
    "p4_li2": "HIGH-QUALITY DECORATIVE SHEETS",
    "p4_li3": "WIDE VARIETY OF DESIGNS",
    "p4_li4": "QUICK AND EASY INSTALLATION",
    "p4_li5": "EASY TO CLEAN",
    "p4_li6": "HIGH RESISTANCE TO MOISTURE AND MOLD",
    "p4_li7": "DRY CLEAN CONSTRUCTION",
    "p4_li8": "HIGH RESISTANCE TO STAINS",

    "product_heading_7": "6 - SANDWICH INSULATED PANELS WITH PRE-PAINTED GALVANIZED STEEL SHEET",
    "p5_li1": "SELF-SUPPORTING PANELS",
    "p5_li2": "EXPANDED POLYSTYRENE (EPS) CORE",
    "p5_li3": "INJECTED POLYURETHANE (PUR AND PIR) CORE",
    "p5_li4": "ROCK WOOL (LDR) CORE",
    "p5_li5": "VARIABLE THICKNESSES BETWEEN 40 AND 200 mm",
    "p5_li6": "SHEET THICKNESS 0.5 mm",
    "p5_li7": "USABLE WIDTH 1.00 / 1.22 m",
    "p5_li8": "VERY EASY TO INSTALL",
    "p5_li9": "DRY CONSTRUCTION",

    "product_heading_8": "7 - FRP FOR TRAILERS",
    "p6_li1": "GREATER CORROSION RESISTANCE THAN ALUMINUM",
    "p6_li2": "GREATER HAIL RESISTANCE THAN ALUMINUM",
    "p6_li3": "MUCH EASIER TO REPAIR THAN METAL LINERS",
    "p6_li4": "GELCOAT FINISH, A UV PROTECTIVE LAYER",
    "p6_li5": "LIGHTWEIGHT AND HIGH MECHANICAL STRENGTH",
    "p6_li6": "LONG SERVICE LIFE",
    "p6_li7": "AVAILABLE IN VARIOUS COLORS",

    "product_heading_9": "8 - CONTAINERS / SHELTERS",
    "p7_li1": "IDEAL FOR WORKSHOP SITE IN ALL INDUSTRIES",
    "p7_li2": "SHELTERS FOR ELECTRICAL AND TELECOMMUNICATIONS EQUIPMENT",

    "benefits_where": "WHERE FRP IS USED",

    "benefits_title": "ADVANTAGES OF USING FRP IN CONSTRUCTION",
    "b3_li1": "ALLOWS THE RENOVATION OF WALLS DETERIORATED BY TIME AND USE",
    "b3_li2": "EASY TO CLEAN",
    "b3_li3": "HIGH RESISTANCE TO MOISTURE AND MOLD",
    "b3_li4": "HIGH RESISTANCE TO CHEMICAL AGENTS",
    "b3_li5": "HIGH RESISTANCE TO STAINS",
    "b3_li6": "HIGH RESISTANCE TO BACTERIAL GROWTH",
    "b3_li7": "FINISHED WITH GELCOAT, AN UV PROTECTIVE LAYER",
    "b3_li8": "VERY EASY TO INSTALL",

    "b4_li1": "COMPLIES WITH HYGIENE AND FOOD SAFETY STANDARDS",
    "b4_li2": "LONG SERVICE LIFE",
    "b4_li3": "ACCESSORIES, MOLDINGS AND RIVETS TO COMPLETE THE INSTALLATION",
    "b4_li4": "INTERNATIONAL CERTIFICATIONS",
    "b4_li5": "HIGH GLOSS AND COLOR PERMANENCE",
    "b4_li6": "DO NOT REQUIRE WET CONSTRUCTION",
    "b4_li7": "VERY LOW MAINTENANCE COST",
    "b4_li8": "AVAILABLE IN VARIOUS COLORS",

    "comparison_title": "DISADVANTAGES OF TRADITIONAL PRODUCTS",

    "comp_h1": "TILES",
    "comp_h2": "SANDWICH PANELS CLAD WITH ALUMINUM OR STAINLESS STEEL",
    "comp_h3": "EPOXY PAINTS",

    "comp_r1_c1": "GROUT LINES IMPOSSIBLE TO CLEAN",
    "comp_r2_c1": "EASILY DAMAGED BY IMPACT",
    "comp_r3_c1": "REQUIRE FREQUENT REPLACEMENT",
    "comp_r4_c1": "WET AND SLOW INSTALLATION",

    "comp_r1_c2": "EXPENSIVE",
    "comp_r2_c2": "IT DENTS AND CORRODES",

    "comp_r1_c3": "HIGH COST PER INSTALLED M2",
    "comp_r2_c3": "NEEDS CONSTANT REPAINT",

    "ad_title_1": "BEFORE AND AFTER",
    "ad_title_2": "BEFORE AND AFTER",
    "ad_title_3": "BEFORE AND AFTER",

    "footer_contact_title": "CONTACT US",
    "cta_quot": "REQUEST A QUOTE",
    "cta_whatsapp": "WHATSAPP",
    "footer_copyright": "© 2025 Refrin. All rights reserved"
};