// scripts/lang_es.js
window.LANG_ES = {
    "page_title": "Refrin — Inicio",
    "nav_productos": "PRODUCTOS",
    "nav_nosotros": "NOSOTROS",
    "nav_contacto": "CONTACTO",
    "hero_title": "REVESTIMIENTOS SANITARIOS PARA PAREDES Y CIELORRASOS",
    "hero_sub": "PANELES DE PRFV (PLÁSTICO REFORZADO FIBRA DE VIDRIO)",
    "empresa_title": "NUESTRA EMPRESA",
    "empresa_p1": "<strong>Fundada en 1943</strong> como consultora de ingeniería para realizar proyectos de obras industriales completas (obras civiles, electromecánicos y de refrigeración industrial).",
    "empresa_p2": "<strong>En 1959</strong> Refrin amplió su actividad con la fabricación e instalación de equipamiento de refrigeración industrial (evaporadores, condensadores, congeladores de placa, recipientes a presión etc.), ofreciendo todo tipo de soluciones para los procesos de enfriado, congelado y almacenamiento de productos alimenticios.",
    "empresa_p3": "<strong>Desde 1993</strong> somos representantes exclusivos para Mercosur de la firma Inglesa Storax Racking System que fue comprada por la Belga Stow group, líder mundial en la provisión de estanterías móviles de alta densidad de almacenamiento para cámaras frías y centros de distribución.",
    "empresa_p4": "También representamos a la firma Alemán <strong>Lamilux</strong>, líder mundial en fabricación de paneles sanitarios de PRFV (Plástico Reforzado Fibra de Vidrio). Hemos sido pioneros en Argentina en importar y colocar material de PRFV, actividad que comenzamos en <strong>1980</strong>.",
    "empresa_p5": "Con una trayectoria de mas de <strong>80 años</strong>, Refrin les ofrece las mejores soluciones para la industria alimenticia.",
    "empresa_image_alt": "Historia de Refrin",

    "productos_title": "NUESTROS PRODUCTOS",
    "product_heading_1": "1 - PANELES TÉRMICOS REVESTIDOS CON LÁMINAS DE PRFV",
    "p1_li1": "Panel autoportante",
    "p1_li2": "Núcleo en poliestireno expandido (EPS)",
    "p1_li3": "Núcleo en poliuretano inyectado (PUR y PIR)",
    "p1_li4": "Núcleo en lana de roca (LDR)",
    "p1_li5": "Espesores variables entre 40 y 200 mm",
    "p1_li6": "Espesor del PRFV entre 1,2 y 2,0 mm",
    "p1_li7": "Ancho útil 1,00 / 1,22 m",
    "p1_li8": "Muy fácil de instalar",
    "p1_li9": "Obra limpia en seco",
    "p1_img_alt": "Foto de un camión de Refrin",

    "product_heading_2": "2 - PLACAS DE PRFV PARA REVESTIMIENTO DE PAREDES",
    "slide_2_1": "PRFV GOFRADO",
    "slide_2_1_img_alt": "Muestra PRFV Gofrado",
    "slide_2_2": "PRFV LISO",
    "slide_2_2_img_alt": "Muestra PRFV Liso",
    "slide_2_3": "PRFV HIGH IMPACT",
    "slide_2_3_img_alt": "Muestra PRFV High Impact",
    "slide_2_4": "PRFV ANTIBAC",
    "slide_2_4_img_alt": "Muestra PRFV Antibac",
    "carousel_caption_title": "",
    "carousel_caption_desc": "",

    "product_heading_3": "2 - PLACAS DE PRFV PARA REVESTIMIENTO DE PAREDES",
    "p2_li1": "ALTA RESISTENCIA A LA HUMEDAD Y AL MOHO",
    "p2_li2": "ALTA RESISTENCIA A LOS AGENTES QUÍMICOS",
    "p2_li3": "FACIL DE LIMPIAR",
    "p2_li4": "ACABADO CON GELCOAT, CAPA PROTECTORA CONTRA LOS RAYOS UV",
    "p2_li5": "ESPESORES DE PLACAS ENTRE 1,00 Y 2,2mm",
    "p2_li6": "FACIL INSTALACION",
    "p2_li7": "CUMPLE CON LAS NORMAS DE HIGIENE E INOCUIDAD ALIMENTICIA",
    "p2_li8": "GRAN BRILLO Y PERMANENCIA DEL COLOR",
    "p2_li9": "MUY BAJO COSTO DE MANTENIMIENTO",
    "p2_img_alt": "Flyer lamilux",

    "product_heading_4": "3 - PLACAS DE PRFV PARA CIELORRASO PARA COCINAS",
    "p3_li1": "TOTALMENTE SANITARIO",
    "p3_li2": "NO NECESITA MANTENIMIENTO",
    "p3_li3": "RAPIDA Y FACIL INSTALACION",
    "p3_li4": "FACIL DE LIMPIAR",
    "p3_li5": "DIMENSIONES: 61 x 61cm",
    "p3_li6": "OBRA LIMPIA EN SECO",
    "p3_li7": "GRILLA METALICA O PLASTICA",
    "p3_li8": "IDEAL PARA COCINAS INDUSTRIALES",
    "p3_li9": "IDEAL PARA COCINAS DE RESTAURANTES Y FAST FOOD",
    "p3_img_alt": "Flyer Cielorraso PRFV",

    "product_heading_5": "4 - ACCESORIOS SANITARIOS",
    "slide_4_1_img_alt": "Muestra ZOCALOS",
    "slide_4_2_img_alt": "Muestra CORTE Y PLEGADO DE CHAPAS",
    "slide_4_3_img_alt": "Muestra 1- MOLDURAS EXTRUIDAS DE PVC",
    "slide_4_4_img_alt": "Muestra 2- MOLDURAS EXTRUIDAS DE PVC",

    "product_heading_6": "5 - PLACAS DE PRFV PARA DECORACION",
    "p4_li1": "PARA OBRAS DE ARQUITECTURA E INTERIORES",
    "p4_li2": "LAMINAS DECORATIVAS DE ALTA CALIDAD",
    "p4_li3": "GRAN VARIEDAD DE DISEÑOS",
    "p4_li4": "RAPIDA Y FACIL INSTALACION",
    "p4_li5": "FACIL DE LIMPIAR",
    "p4_li6": "ALTA RESISTENCIA A LA HUMEDAD Y AL MOHO",
    "p4_li7": "OBRA LIMPIA EN SECO",
    "p4_li8": "ALTA RESISTENCIA A LAS MANCHAS",

    "product_heading_7": "6 - PANELES TERMICOS REVESTIDOS CON CHAPA DE ACERO GALVANIZADA REPINTADA",
    "p5_li1": "PANELES AUTOPORTANTES",
    "p5_li2": "NUCLEO EN POLIESTIRENO EXPANDIDO (EPS)",
    "p5_li3": "NUCLEO EN POLIURETANO INYECTADO (PUR Y PIR)",
    "p5_li4": "NUCLEO EN LANA DE ROCA (LDR)",
    "p5_li5": "ESPESORES VARIABLES ENTRE 40 Y 200mm",
    "p5_li6": "ESPESOR DE LA CHAPA DE 0,5mm",
    "p5_li7": "ANCHO UTIL 1,00 / 1,22mm",
    "p5_li8": "MUY FACIL DE INSTALAR",
    "p5_li9": "OBRA LIMPIA EN SECO",
    "p5_img_alt": "Flyer Cielorraso PRFV",

    "product_heading_8": "7 - PRFV PARA TRAILERS",
    "p6_li1": "MAYOR RESISTENCIA A LA CORROSION QUE EL ALUMNIO",
    "p6_li2": "MAYOR RESISTENCIA AL GRANIZO QUE EL ALUMINIO",
    "p6_li3": "REPARACION MAS FACIL QUE LA DE LOS REVESTIMIENTOS METALICOS",
    "p6_li4": "ACABADO CON GELCOAT, CAPA PROTECTORA CONTRA LOS RAYOES UV",
    "p6_li5": "BAJO PESO Y ALTA RESISTENCIA MECANICA",
    "p6_li6": "LARGA VIDA UTIL",
    "p6_li7": "DISPONIBLE EN VARIOS COLORES",

    "product_heading_9": "8 - CONTENEDORES / SHELTERS",
    "p7_li1": "IDEAL PARA OBRADORES EN TODAS LAS INDUSTRIAS",
    "p7_li2": "SHELTERS PARA EQUIPOS ELECTRICOS Y DE TELECOMUNICACIONES",

    "benefits_where": "DONDE SE USA EL PRFV",
    "b1_li1": "PLANTAS PROCESADORES EN LA INDUSTRIA: CARNICA - AVICOLA - LACTEA - PESQUERA - PANIFICACION - BEBIDAS CON Y SIN ALCOHOL",
    "b1_li2": "CAMARAS FRIAS",
    "b1_li3": "INDUSTRIA FARMACEUTICA Y LABORATORIOS",
    "b1_li4": "COCINAS DE RESTAURANTES Y FAST FOOD",
    "b1_li5": "HOSPITALES, CLINICAS, SANATORIOS, QUIROFANOS",
    "b1_li6": "ESCUELAS",
    "b1_li7": "CONTENEDORES / SHELTERS",
    "b2_li1": "SUPERMERCADOS",
    "b2_li2": "LAVADEROS DE AUTOS",
    "b2_li3": "PLANTAS DE PROCESOS QUIMICOS",
    "b2_li4": "TRANSPORTE",
    "b2_li5": "HOTELES",
    "b2_li6": "DEPOSITOS INDUSTRIALES",
    "b2_li7": "VESTUARIOS INDUSTRIALES",
    "b2_li8": "TRAILERS, \"CASAS RODANTES\"",

    "benefits_title": "VENTAJAS DE UTILIZAR PRFV EN LA CONSTRUCCIÓN",
    "b3_li1": "Permite renovar a nuevas las paredes deterioradas por el transcurso del tiempo y uso",
    "b3_li2": "Fácil de limpiar",
    "b3_li3": "Alta resistencia a la humedad y al moho",
    "b3_li4": "Alta resistencia a los agentes químicos",
    "b3_li5": "Alta resistencia a las manchas",
    "b3_li6": "Alta resistencia al crecimiento bacteriano",
    "b3_li7": "Acabado con gelcoat, capa protectora contra los rayos UV",
    "b3_li8": "Muy fácil de instalar",
    "b4_li1": "Cumple con las normas de higiene e inocuidad alimenticia",
    "b4_li2": "Larga vida útil",
    "b4_li3": "Accesorios, molduras y remaches para completar la instalación",
    "b4_li4": "Certificaciones internacionales",
    "b4_li5": "Gran brillo y permanencia del color",
    "b4_li6": "No necesita realizar obra húmeda",
    "b4_li7": "Muy bajo costo de mantenimiento",
    "b4_li8": "Disponible en varios colores",

    "comparison_title": "DESVENTAJAS DE LOS PRODUCTOS TRADICIONALES",
    "comp_h1": "Azulejos",
    "comp_h2": "Paneles Sandwich revestidos<br>con aluminio o acero inoxidable",
    "comp_h3": "Pinturas Epóxicas",
    "comp_r1_c1": "Juntas permanentemente sucias",
    "comp_r1_c2": "Alto costo",
    "comp_r1_c3": "Alto costo por m²",
    "comp_r2_c1": "Se dañan fácilmente por impacto",
    "comp_r2_c2": "Propenso a abollarse y corroerse con el tiempo",
    "comp_r2_c3": "Requiere repintado frecuente y mantenimiento constante",
    "comp_r3_c1": "Hay que reemplazarlos frecuentemente",
    "comp_r4_c1": "Instalación húmeda y lenta",

    "ad_title_1": "ANTES Y DESPUES",
    "ad_title_2": "ANTES Y DESPUES",
    "ad_title_3": "ANTES Y DESPUES",
    "ad1_before_alt": "Antes - ejemplo 1",
    "ad1_after_alt": "Despues - ejemplo 1",
    "ad2_before_alt": "Antes - ejemplo 2",
    "ad2_after_alt": "Despues - ejemplo 2",
    "ad3_before_alt": "Antes - ejemplo 3",
    "ad3_after_alt": "Despues - ejemplo 3",

    "footer_address": "Talcahuano 768 9° Piso (C1013) | Buenos Aires, Argentina",
    "footer_phone": "(+54-11) 4374-8669",
    "footer_contact_title": "CONTÁCTENOS",
    "cta_quot": "Pedir Cotización →",
    "cta_whatsapp": "Mensaje por WhatsApp",
    "cta_email": "info@refrin.com.ar",
    "footer_links_title": "Enlaces Rápidos",
    "footer_link_home": "Inicio",
    "footer_link_products": "Productos",
    "footer_link_about": "Nosotros",
    "footer_link_cases": "Casos de Éxito",
    "footer_link_contact": "Contacto",
    "footer_copyright": "© 2025 Refrin. Todos los derechos reservados",
    "footer_privacy": "Política de Privacidad",
    "footer_terms": "Términos de Servicio",

    "img_logo_alt": "Refrin logo",
    "footer_logo_alt": "Refrin logo"
};